### ISSUE TITLE
Document API

### ISSUE THREAD

**Issue by Ragnar-H** [veritus/veritus-backend#53]
Spawned from discussion in #20 

# Description

With an ever growing API interface, it will be a great benefit if developers can get a quick overview of what the API is capable of.

# Thoughts

In my mind a successful documentation gives quick access to example input/output, allows devs to make HTTP calls, is autogenerated (or at the very least, lives in the code).

My reasoning behind the need for autogeneration, is that writing documentation takes time, and is very often overlooked when developing, and quite often out of date.
Misinformation is worse than no information.

# Todos
- [ ] Investigate available tools. (Good place to start is the [official](http://www.django-rest-framework.org/topics/documenting-your-api/) django-rest documentation)
- [ ] Outline short summary of these tools with, pros | cons, pricing, what needs to be done by dev team
- [ ] Outline how developers should keep documentation up to date. (Update PR template?)
- [ ] Document existing endpoints

**Comment by Ragnar-H** [comment]
@skabbi I've outlined how I'd like to see this issue resolved.

But this is very biased.
I think you should take ownership of this and run with it.

**Comment by AriHrannar** [comment]
Autogenerated is a must I think. Its tedious to keep it up manually and something always gets forgotten.

**Comment by skabbi** [comment]
Autogenerated it will be then. @AriHrannar could you send me your Postman collection to help me test the API doc that will be created.

**Comment by AriHrannar** [comment]
[Apiary](https://apiary.io/) might be something cool to look into. Maybe Google-ing around will give some good hits as well :) 

I did share postman and [this](https://documenter.getpostman.com/view/686947/politec/6mxYvpH) was the result. Its probably not everything and I am not even sure everything is correct :) its been such a long time since I did any webservice stuff in the backend :(

**Comment by skabbi** [comment]
**Investigate available tools**
I looked over [Apiary](https://apiary.io/) and although it would probably fit our needs, for now, it has [payment plans](https://apiary.io/plans).
I also looked over the [official Django REST documentation page](http://www.django-rest-framework.org/topics/documenting-your-api/) and decided on [Django REST Swagger](https://github.com/marcgibbons/django-rest-swagger#django-rest-swagger). Mainly because I had heard good things of Swagger and it looked the prettiest.
I feel that other tools will be at best as good as Swagger, so not worth spending too much time on them.

**Outline short summary of these tools with, pros | cons, pricing, what needs to be done by dev team**
 Apiary: 
- pros: Backed by Oracle. Can expect excellent support and documentation.
- cons: Cost. Get the feeling it's not made for small teams/projects.

Django REST Swagger: 
- pros: Free. Seems widely used and documented.
- cons: None?

**Outline how developers should keep documentation up to date**
Using the minimal setup for autogeneration, as described [here](http://hirelofty.com/blog/auto-generate-swagger-docs-your-django-api/), gives us a lot with no work.

**Document existing endpoints**
By only adding a few lines of code to `urls.py`, it seems like every endpoint is now documented and testable via Swagger by opening http://localhost:8000 in the browser.

@AriHrannar @Ragnar-H I've created the branch `infrastructure/document-api`, but I don't seem to have permission to push code to the repo.
Also, how do I move issues to "In Progress"?

**Comment by Ragnar-H** [comment]
Awesome work 🙌

I suppose the only thing we need to keep up to date are the docstrings mentioned in the [article](http://hirelofty.com/blog/auto-generate-swagger-docs-your-django-api/)

> I've created the branch infrastructure/document-api, but I don't seem to have permission to push code to the repo

My bad, that should be fixed

> Also, how do I move issues to "In Progress"?

You can use the "Pipeline" in the top corner of issues (see screenshot).
But I get a kick out of dragging the tickets around in the Zenhub "Board" view 😊

<img width="1076" alt="screen shot 2017-07-28 at 10 24 47" src="https://user-images.githubusercontent.com/22854722/28709222-b6ff7cdc-737f-11e7-9759-1433a7cfb129.png">


Looking forward to see your work 🎊

**Comment by AriHrannar** [comment]
@skabbi I would recommend installing [zenhub](https://chrome.google.com/webstore/detail/zenhub-for-github/ogcgkffhplmphkaahpmffcafajaocjbd) for Chrome (should be available for Firefox and Opera as well if that is what you are into). Then you will get some additional tabs in the repo (like board) :)

**Comment by skabbi** [comment]
@Ragnar-H  I'm still unable to push code, can you double check it has been fixed?

@AriHrannar I have ZenHub installed, but it seems I don't have permission to change the status of an issue.

**Comment by skabbi** [comment]
[Created pull request](https://github.com/veritus/veritus-backend/pull/59). 

@AriHrannar @Ragnar-H Please look over it and tell me your thoughts. I also added, hopefully accurate,  docstrings to make the endpoints more descriptive.

**Comment by skabbi** [comment]
[Pull request merged](https://github.com/veritus/veritus-backend/pull/59#pullrequestreview-54366801). Closing issue.

**Comment by Ragnar-H** [comment]
\o/
